#!/system/bin/sh
MODDIR=${0%/*}/..

init_config() {
    cat $MODDIR/config.conf >/dev/null 2>&1 || touch $MODDIR/config.conf

    . $MODDIR/config.conf

    LIST_VAR='
LANGUAGE=ru
THEME=oled
LOG_LEVEL=INFO

SWAP_ENABLED=false
SWAP_SIZE_GB=1
OVERHEAD_GB=0.3

ZRAM_ENABLED=true
ZRAM_RATIO=2.10
ZRAM_ALGORITHM=zstd
MAX_COMP_STREAMS=6
ZRAM_AUTO_TUNE=false
ZRAM_STREAMS_AUTO=true
ZRAM_EARLY_INIT=false
ZRAM_DEDUP=true
ZRAM_SWAP_PRIORITY=100
ZRAM_WRITEBACK_THRESHOLD=0.5
ZRAM_MEMORY_LIMIT=0.8

SWAPPINESS=90
CACHE_PRESSURE=45
DIRTY_RATIO=35
DIRTY_BACKGROUND_RATIO=5
DYNAMIC_SWAPPINESS=false
EXTRA_TUNING=false
PERFORMANCE_MODE=false

VM_COMPACTION_PROACTIVE=true
VM_PAGE_CLUSTER=3
VM_EXTRA_FREE_KBYTES=12288
VM_DIRTY_EXPIRE_CENTISECS=3000
VM_DIRTY_WRITEBACK_CENTISECS=500
VM_MIN_FREE_KBYTES=67584
VM_WATERMARK_SCALE_FACTOR=125

AI_OPTIMIZER_ENABLED=true
PERFORMANCE_PROFILE=balanced
THERMAL_CONTROL_ENABLED=true
PROCESS_AWARE_OPTIMIZATION=true
CONTEXT_AWARE_OPTIMIZATION=true

PERFORMANCE_APPS=
BACKGROUND_APPS=

HUGEPAGES_ENABLED=true
HUGEPAGES_COUNT=16
HUGEPAGES_SIZE_MB=2
HUGEPAGES_AUTO_MANAGE=true
    '

    for var in $LIST_VAR; do
        variable="${var%%:*}"
        value="${var#*:}"
        
        if [ -z "$(eval echo \$$variable)" ]; then
            echo "$variable=$value" >> $MODDIR/config.conf
            eval "$variable=\"$value\""
        fi
    done

    . $MODDIR/config.conf
}
