#!/system/bin/sh
MODDIR=${0%/*}/..

init_config() {
    local config_file="$MODDIR/config.conf"
    
    if [ ! -f "$config_file" ]; then
        mkdir -p "$(dirname "$config_file")"
        cat > "$config_file" << 'EOF'
SWAP_ENABLED=false
SWAP_SIZE_GB=1.0
OVERHEAD_GB=0.3
ZRAM_ENABLED=true
ZRAM_RATIO=1.5
ZRAM_ALGORITHM=lz4
MAX_COMP_STREAMS=4
SWAPPINESS=100
CACHE_PRESSURE=100
DIRTY_RATIO=20
DIRTY_BACKGROUND_RATIO=10
EXTRA_TUNING=false
DYNAMIC_SWAPPINESS=true
PERFORMANCE_MODE=false
ZRAM_AUTO_TUNE=false
LOG_LEVEL=INFO
VM_DIRTY_WRITEBACK_CENTISECS=1500
VM_DIRTY_EXPIRE_CENTISECS=3000
VM_PAGE_CLUSTER=0
VM_LAPTOP_MODE=0
VM_OOM_KILL_ALLOCATING_TASK=0
VM_PANIC_ON_OOM=0
VM_OVERCOMMIT_MEMORY=1
VM_OVERCOMMIT_RATIO=50
VM_WATERMARK_SCALE_FACTOR=10
KERNEL_THREADS_MAX=0
ZRAM_COMPRESSION_LEVEL=1
ZRAM_MEMORY_LIMIT=4G
SWAP_PRIORITY=10
ZRAM_PRIORITY=100
IO_SCHEDULER_TUNE=false
CPU_BOOST=false
NETWORK_TUNE=false
EOF
    fi

    . "$config_file"
    
    for var in $(set | grep -E '^[A-Z_]+=' | cut -d= -f1); do
        case "$var" in
            SWAP_ENABLED|SWAP_SIZE_GB|OVERHEAD_GB|ZRAM_ENABLED|ZRAM_RATIO|ZRAM_ALGORITHM|MAX_COMP_STREAMS|SWAPPINESS|CACHE_PRESSURE|DIRTY_RATIO|DIRTY_BACKGROUND_RATIO|EXTRA_TUNING|DYNAMIC_SWAPPINESS|PERFORMANCE_MODE|ZRAM_AUTO_TUNE|LOG_LEVEL|VM_DIRTY_WRITEBACK_CENTISECS|VM_DIRTY_EXPIRE_CENTISECS|VM_PAGE_CLUSTER|VM_LAPTOP_MODE|VM_OOM_KILL_ALLOCATING_TASK|VM_PANIC_ON_OOM|VM_OVERCOMMIT_MEMORY|VM_OVERCOMMIT_RATIO|VM_WATERMARK_SCALE_FACTOR|KERNEL_THREADS_MAX|ZRAM_COMPRESSION_LEVEL|ZRAM_MEMORY_LIMIT|SWAP_PRIORITY|ZRAM_PRIORITY|IO_SCHEDULER_TUNE|CPU_BOOST|NETWORK_TUNE)
                eval "export $var"
                ;;
        esac
    done
}
