#ifndef KERNEL_TUNING_VERSION_H
#define KERNEL_TUNING_VERSION_H

#define KERNEL_TUNING_SERVICE_NAME "nextramd-kernel-tn-service"
#define KERNEL_TUNING_SERVICE_VERSION "1.0.953_(26.10.2025)"
#define KERNEL_TUNING_BUILD_DATE __DATE__
#define KERNEL_TUNING_BUILD_TIME __TIME__

#endif
